"""add step_attempts history, drop processing_steps.error

Revision ID: 8513406c206f
Revises: 5abbb235c600
Create Date: 2026-07-04 15:51:25.793597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8513406c206f'
down_revision: Union[str, Sequence[str], None] = '5abbb235c600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_attempts',
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['processing_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_attempts_step_id'), 'step_attempts', ['step_id'], unique=False)
    op.drop_column('processing_steps', 'error')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_steps', sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_step_attempts_step_id'), table_name='step_attempts')
    op.drop_table('step_attempts')
    # ### end Alembic commands ###
